FROM node:20.12.2-bookworm-slim AS base
RUN npm i -g pnpm
WORKDIR /app

FROM base AS builder
ENV NODE_ENV=development
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY prisma ./prisma
RUN pnpm i && pnpx prisma generate
COPY . .
RUN pnpm build

FROM base as runner
ENV NODE_ENV=production
RUN apt-get -qy update && apt-get -qy install openssl
COPY package.json ./
COPY pnpm-lock.yaml ./
RUN pnpm i
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
ENV PORT=3333
EXPOSE 3333
ENV HOSTNAME="0.0.0.0"
CMD [ "pnpm", "start:prod" ]